;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	avy-goto-char-2
	beginning-of-buffer
	embark-act
	embrace-add
	emms-tag-editor-submit
	indent-for-tab-command
	magit-stage
	my-scroll-one-line-down
	my-scroll-one-line-up
	my-set-cycle-mark
	org-ctrl-c-ctrl-c
	org-cycle
	org-delete-char
	org-force-self-insert
	org-kill-line
	org-metadown
	org-metaleft
	org-metaright
	org-open-line
	org-self-insert-command
	org-shifttab
	replace-string
	wdired--self-insert
	wdired-capitalize-word
	wdired-downcase-word
	wdired-exit
	wdired-finish-edit
	wdired-upcase-word
	xah-backward-left-bracket
	xah-beginning-of-line-or-block
	xah-comment-dwim
	xah-copy-line-or-region
	xah-cut-line-or-region
	xah-end-of-line-or-block
	xah-extend-selection
	xah-fly-command-mode-activate
	xah-fly-insert-mode-activate
	xah-forward-right-bracket
	xah-insert-space-before
	xah-paste-or-paste-previous
	xah-select-block
	xah-select-line
	xah-shrink-whitespaces
	xah-smart-delete
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	iedit-switch-to-mc-mode
	my-force-fullscreen-toggle
	xah-next-window-or-frame
	))
