;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	magit-stage
	org-ctrl-c-ctrl-c
	org-kill-line
	org-metadown
	org-self-insert-command
	replace-string
	wdired--self-insert
	wdired-exit
	wdired-finish-edit
	wdired-upcase-word
	xah-backward-left-bracket
	xah-beginning-of-line-or-block
	xah-comment-dwim
	xah-copy-line-or-region
	xah-cut-line-or-region
	xah-end-of-line-or-block
	xah-fly-command-mode-activate
	xah-fly-insert-mode-activate
	xah-forward-right-bracket
	xah-insert-space-before
	xah-paste-or-paste-previous
	xah-shrink-whitespaces
	xah-smart-delete
	))

(setq mc/cmds-to-run-once
      '(
	iedit-switch-to-mc-mode
	))
