[manager]
ratio          = [1, 3, 4]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true
scrolloff      = 8

[preview]
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1

[opener]
editor = [
  { run = 'emacsclient -c -a -- "$@"', desc = "Emacs (GUI)", orphan = true },
]

edit_sh = [
  { run = 'emacsclient -c -a -- "$@"', desc = "Emacs (GUI)",      orphan = true },
  { run = 'emacsclient -nw "$@"',      desc = "Emacs (Terminal)", block = true  },
  { run = 'nano "$@"',                 desc = "Nano",             block = true  },
  { run = 'kate "$@"',                 desc = "Kate",             orphan = true },
]
edit = [
  { run = 'emacsclient -c -a -- "$@"', desc = "Emacs (gui)",      orphan = true },
  { run = 'emacsclient -nw "$@"',      desc = "Emacs (terminal)", block = true  },
  { run = 'nano "$@"',                 desc = "Nano",             block = true  },
]
open_md = [
  { run = 'kitty --class md_floating -e mdfried "$@" &', desc = "mdfried", orphan = true },
]
open_pdf = [
  { run = 'zathura "$@"', desc = "Zathura", orphan = true },
]
open_video = [
  { run = 'mpv "$@"', desc = "mpv", orphan = true },
]
open_audio = [
  { run = 'mpv "$@"', desc = "mpv", orphan = true },
]
open_image = [
  { run = 'sxiv -af "$@"', desc = "sxiv", orphan = true },
]
extract = [
  { run = 'atool --extract --each -- "$@"', desc = "Extract (atool)" },
]
list_archive = [
  { run = 'atool --list --each -- "$@" | "$PAGER"', desc = "List (atool)", block = true },
]

[open]
prepend_rules = [
  { url  = "*.sh",                         use = "edit_sh" },
  { url  = "*.md",                         use = ["open_md", "edit"] },
  { url  = "*.py",                         use = "edit" },
  { url  = "*.org",                        use = "edit" },
  { mime = "application/pdf",              use = "open_pdf" },
  { mime = "video/*",                      use = "open_video" },
  { mime = "audio/*",                      use = "open_audio" },
  { mime = "image/*",                      use = "open_image" },
  { mime = "application/zip",              use = ["extract", "list_archive"] },
  { mime = "application/x-tar",            use = ["extract", "list_archive"] },
  { mime = "application/x-rar",            use = ["extract", "list_archive"] },
  { mime = "application/x-7z-compressed",  use = ["extract", "list_archive"] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912
image_bound      = [0, 0]
suppress_preload = false

[log]
enabled = false